### PR TITLE
Fix byte-compilation errors

### PR DESCRIPTION
**Pull request by akirak**
Hello, I tried to build files in this repository and encountered some compilation errors.

- `org-num.el` seems to be a relatively new addition to org. It fails to build on Emacs 27.2, so I worked around it.
- Variables such as `org-indent--deepest-level` are unavailable until `org-indent.el` is loaded. The library should be explicitly loaded.
- You have to load `org-element.el` if you use functions such as `org-element-map`. They are not autoloaded.
- The trailing whitespace and misindentation are fixed. I'd suggest you turn on `aggressive-indent-mode` when you write elisp.

I also added the autoload magic to `writer-mode`, as the user don't have to load `nano-writer.el` until he/she uses the mode.

### CODE REVIEW

**Comment by rougier** [comment]
Oh nice, many thanks.
